
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 172.30.0.2
  port: 5432

development:
  adapter: postgresql
  encoding: unicode
  database: instagram_development
  pool: 5
  username: admin
  password: admin
  host: 172.30.0.2
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: instagram_test
  pool: 5
  username: admin
  password: admin
  host: 172.30.0.2
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: instagram_production
  pool: 5
  username: admin
  password: admin
  host: 172.30.0.2
  port: 5432
